usr/lib/lib*.so.*
usr/share/communicatord/services/snaprfs.service
usr/bin/rfs                                       usr/bin/
usr/sbin/snaprfs                                  usr/sbin/
conf/snaprfs.conf                                 etc/snaprfs/
conf/logger/snaprfs.conf                          etc/snaprfs/logger/
conf/logger/README.md                             etc/snaprfs/logger/snaprfs.d/
conf/config-README.md                             etc/snaprfs/snaprfs.d/
